### ISSUE TITLE
mdf5 hash error on SIMPLE_TRIM_output.nc download

### ISSUE THREAD

**Issue by rabernat** [annieleal/rces-final-project#2]
When tried to run your notebook, I experienced the following error:

```python
simple_trim_url = 'http://tdevries.eri.ucsb.edu/wp-content/uploads/2018/03/SIMPLE_TRIM_output.nc'

file_path = pooch.retrieve(url=simple_trim_url,
                          known_hash='md5:75487e25bfe7448736883a26b697ba81')
```

> ValueError: MD5 hash of downloaded file (e4a0a4525472949384e03b3f13eddc14-SIMPLE_TRIM_output.nc) does not match the known hash: expected md5:75487e25bfe7448736883a26b697ba81 but got 95467187b0d29e66b4d5ed0c58a101af. Deleted download for safety. The downloaded file may have been corrupted or the known hash may be outdated.

The error can be fixed by setting `known_hash='md5:95467187b0d29e66b4d5ed0c58a101af'` instead.

For reference, this hash is used to [verify data integrity](https://en.wikipedia.org/wiki/MD5). I'm not sure where you got the original hash. Do you have any reason to think that the file has changed recently or will change in the future?

If you can fix this and push an update to your notebook, I won't deduct any points.

**Comment by annieleal** [comment]
> When tried to run your notebook, I experienced the following error:
> 
> ```python
> simple_trim_url = 'http://tdevries.eri.ucsb.edu/wp-content/uploads/2018/03/SIMPLE_TRIM_output.nc'
> 
> file_path = pooch.retrieve(url=simple_trim_url,
>                           known_hash='md5:75487e25bfe7448736883a26b697ba81')
> ```
> 
>  > ValueError: MD5 hash of downloaded file (e4a0a4525472949384e03b3f13eddc14-SIMPLE_TRIM_output.nc) does not match the known hash: expected md5:75487e25bfe7448736883a26b697ba81 but got 95467187b0d29e66b4d5ed0c58a101af. Deleted download for safety. The downloaded file may have been corrupted or the known hash may be outdated.
> 
> The error can be fixed by setting `known_hash='md5:95467187b0d29e66b4d5ed0c58a101af'` instead.
> 
> For reference, this hash is used to [verify data integrity](https://en.wikipedia.org/wiki/MD5). I'm not sure where you got the original hash. Do you have any reason to think that the file has changed recently or will change in the future?
> 
> If you can fix this and push an update to your notebook, I won't deduct any points.

This should be fixed now. It is just a link on their website, so I cannot tell if they have updated this recently. 

Thank you for your help and understanding!
